// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyText(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetModelDownloadStatus():Promise<main.ModelDownloadStatus>;

export function GetRuntimeStatus():Promise<main.RuntimeStatus>;

export function ListModels():Promise<Array<main.ModelInfo>>;

export function OpenDataDirectory():Promise<void>;

export function PrepareRuntime():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function Translate(arg1:main.TranslateRequest):Promise<main.TranslateResult>;
