// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetModelDownloadStatus() {
  return window['go']['main']['App']['GetModelDownloadStatus']();
}

export function GetRuntimeStatus() {
  return window['go']['main']['App']['GetRuntimeStatus']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function OpenDataDirectory() {
  return window['go']['main']['App']['OpenDataDirectory']();
}

export function PrepareRuntime() {
  return window['go']['main']['App']['PrepareRuntime']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function Translate(arg1) {
  return window['go']['main']['App']['Translate'](arg1);
}
